#!/usr/bin/python
# coding: UTF-8
#作者 蒋明
#作用 ucncity教程下载工具
#pip install pywinauto
#P6 - Time Series Forecasting
#http://www.youtubecomtomp3.com/zh/YouTube-to-MP4.php
#日期 2016-12-16
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
#import win32gui
import os
from selenium.webdriver.support.ui import Select
#import win32con
import time,platform,sys, getopt,paramiko,random,re
#import socks  
#import socket 
#import requests

#back=socket.socket
#socks.set_default_proxy(socks.SOCKS5, "127.0.0.1",1080)
#print(requests.get('http://ifconfig.me/ip').text)
import psycopg2
conn = psycopg2.connect(database="laicunba_test", user="postgres", password="D8TBaUZhDG7xaXw3Ov7LPW1HUcmO31", host="120.27.145.175", port="12345")
cur = conn.cursor()#该程序创建一个光标将用于整个数据库使用Python编程。
cur.execute("update lcb_user set pid='' where pid='320301198502169142';update lcb_user_bank set bank_card_no='' WHERE bank_card_no='6222020111122220000';")  
conn.commit()
conn.close() 


invite=272966
argv=sys.argv[1:]
try:
  opts, args = getopt.getopt(argv,"i:")
except getopt.GetoptError:
  print ('test.py -i <inputfile> -o <outputfile>')
  sys.exit(2)
for opt, arg in opts:
  if opt in ("-i","--invite"):
    invite = arg
		
		
		
url="test.laicunba.com"
tel=""

d = webdriver.Chrome()
d.implicitly_wait(3)
url="http://"+url+"/"
d.get(url+"h5/regist.jsp")
tel="132"+str(random.randint(10000000,99999999))

d.find_element_by_id("mobileInput").send_keys(tel)
print ("手机号"+tel)
d.find_element_by_id("loginPwdInput").send_keys("123456")
d.find_element_by_id("inviteFromInput").send_keys(invite)
d.find_element_by_id("btnGetVerfityCode").click()
time.sleep(1)
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect("test.laicunba.com", 22,'root', '0db16d1f799dd6420fdf6f1e00c7aa58')
stdin, stdout, stderr = ssh.exec_command("tail -n 100  /opt/logs/laicunba_web/laicunba_we.log|grep -v 'rid'")
line=stdout.read().strip().decode('utf-8')
#print(line)
matchObj = re.match( r'[\s\S]*\[(.{4})\]', line, re.M|re.I)
print (matchObj)
if matchObj:
  d.find_element_by_id("picVerifyCodeInput").send_keys(matchObj.group(1))
  time.sleep(1)
  d.find_element_by_id("btnGetVerfityCode").click()
  time.sleep(1)
  stdin, stdout, stderr = ssh.exec_command("tail -n 100  /opt/logs/laicunba_web/laicunba_we.log|grep -v 'rid'")
  line=stdout.read().strip().decode('utf-8')
  ssh.close()
  matchObj = re.match( r'[\s\S]*(\d{6})', line, re.M|re.I)
  print (matchObj)
  if matchObj:
    print (matchObj.group(1))
    d.find_element_by_id("verifyCodeInput").send_keys(matchObj.group(1))
    d.find_element_by_id("btnRegist").click()
    time.sleep(5)
    print (d.current_url)
  else:
    d.quit()
    exit(1)


  
  
  



#d.get(url+"h5/sui_cun_bao_detail.htm")
#d.find_element_by_id("btnBuyNow").click()

url="http://test.laicunba.com/h5/bid_form.htm?id=f7635078-3254-46e2-8bf1-a3d120342b7a&_channel=weixin"
d.get(url)
d.find_element_by_id("buyAmountInput").send_keys("1000")
d.find_element_by_id("nameInput").send_keys(u'张宝')
d.save_screenshot('D:\\selenium\\screenshot.png')
d.find_element_by_id("pidInput").send_keys("320301198502169142")
Select(d.find_element_by_id("bankSelect")).select_by_index(1)
d.find_element_by_id("bankCardNoInput").send_keys("6222020111122220000")
d.find_element_by_id("btnSubmit").click()
time.sleep(10)
d.save_screenshot('c:\\screenshot1.png')
d.find_element_by_css_selector("input#btnSms").click()
d.find_element_by_css_selector("#iptSmscode").send_keys("201603")
d.save_screenshot('c:\\screenshot2.png')
time.sleep(1)
d.find_element_by_id("btnPay").click()
time.sleep(4)
d.find_element_by_id("btnToMerchant").click()

d.quit()
#btnPay#btnPay
#


